exclude:
  - "Gemfile"
  - "Gemfile.lock"
  - "README.md"
  - "LICENSE.md"
  - "*.gemspec"
  - .gitignore

gems:
  - jekyll-assets

title: Kapil Sharma
email: ------------------
description: Data Scientist, Math Geek, Programmer, Musician
baseurl: ""
url: http://www.sharmakapil.com
author: Kapil Sharma
street_address: ------------------------
city: Chicago
state: IL
zip_code: 60605
country: United States of America
phone: +1-312-566-7843

tiles-count: 6

# social settings
500px_url:
facebook_url:
github_url: https://github.com/kapilsh
gitlab_url:
googleplus_url:
instagram_url:
linkedin_url: https://www.linkedin.com/in/kapil-sharma-90094015/
pinterest_url:
slack_url:
twitter_url: https://twitter.com/_k_sharma

highlighter: rouge

# build settings
markdown: kramdown

sass:
  style: compressed
